name: vascular-segment-sampler
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-image
  - scikit-learn
  - pyyaml
  - tqdm
  - simpleitk
  - vtk
  - h5py
  - nibabel
  - pydicom
  - requests
  - opencv
  - pip:
      - dicom2nifti
      - python-gdcm

